Vp/feature wp cli doc
axioned/handbook pull request #25
Opened 2022-12-20 07:55 UTC by pvaishnaviprdxn

2022-12-20 07:58 UTC, yvipinaxioned requested changes

2022-12-20 07:58 UTC, yvipinaxioned commented on docs/decision-records/wp-cli.md
> +id: CLI
Can we use the official name as `WP-CLI` everywhere?

2022-12-20 10:17 UTC, smehboobprdxn commented on docs/decision-records/wp-cli.md
> +**For Linux:**
for Linux and Ubuntu it should be same if so can we club its contradicting (looks like missing command for ubuntu)

2022-12-20 10:17 UTC, smehboobprdxn commented on docs/decision-records/wp-cli.md
> +# Overview
need to revisit the heading hierarchy

2022-12-20 10:17 UTC, smehboobprdxn commented on docs/decision-records/wp-cli.md
> +
The custom command topic is not covered which we used for installing the setup in our WordPress starter repo

can you please add about that how we can create and use custom CLI commands

2022-12-23 14:03 UTC, yvipinaxioned requested changes

2022-12-23 14:03 UTC, yvipinaxioned commented on docs/decision-records/wp-cli.md
> +- UNIX-like environment (OS X, Linux, FreeBSD, Cygwin); limited support in Windows
`limited support in Windows` can we list down things that aren't supported or attach any reference links? 
And if we are confident that our use cases are covered then maybe we can remove this line?

2022-12-27 06:17 UTC, smehboobprdxn approved these changes

2022-12-27 06:32 UTC, smehboobprdxn approved these changes

2022-12-27 18:02 UTC, yvipinaxioned approved these changes

2022-12-28 09:18 UTC, merged